version: "3"
services:
    frontend:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: react
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
    backend:
        container_name: backend
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        ports:
            - "5000:3000"
        volumes:
            - ./server:/app
    db:
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootPassword
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "8889:3306"
        expose:
            -   "8889"
volumes:
    db-data:
